name: "deploy"
on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ win10-x64, linux-x64 ]
    steps:
      - uses: actions/checkout@v2

      - name: Obtain NativeLibs
        run: |
          curl -1 -O 'https://dl.cloudsmith.io/public/vignette/vg-prebuiltlibs/raw/names/vignette.NativeLibs/versions/2020.1027.0/vignette.NativeLibs.zip'
          unzip vignette.NativeLibs.zip

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Publish
        run: |
          dotnet tool restore
          dotnet cake ./build/build.cake --bootstrap
          dotnet cake ./build/build.cake -target=Build -runtime=${{ matrix.runtime }} -configuration=Release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: vignette-${{ github.ref }}-${{ matrix.runtime }}
          path: ./vignette.Desktop/bin/x64/Release/netcoreapp3.1/${{ matrix.runtime }}/publish/*


  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Pack Releases
        run: |
          zip -r vignette-${{github.ref}}-linux-64.zip vignette-${{github.ref}}-linux-x64
          zip -r vignette-${{github.ref}}-win10-64.zip vignette-${{github.ref}}-win10-x64

      - name: Publish 
        uses: joabalea/App-Center-action@v1.0.2
        with:
          command: appcenter distribute --group public -f ./*.zip -r CHANGELOG.md
          token: ${{secrets.VS_APP_CENTER_TOKEN}}

  alert:
    needs: [ deploy ]
    runs-on: ubuntu-latest
      - name: Alert
        uses: tsickert/discord-webhook@v1.0.1
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL_STABLE}}
          content: "Hey @everyone! This is your local Insider messenger! This is a test message for Discord-based alerts. If you see something like this in the near future, check the Appcenter!"
